### ISSUE TITLE
Update all files with consistent naming conventions for React and CSS.

### ISSUE THREAD

**Issue by HampusAndersson01** [HampusAndersson01/Parameter-Database#135]
## Description

We need to update all files with consistent naming conventions for React and CSS. We will use PascalCase for React components and camelCase for CSS and other files.

## Additional Information

This article from freecodecamp.org provides some useful information about CSS naming conventions that will save you hours of debugging .

## Tasks

- [x] Research best practices for naming conventions in React and CSS.
- [ ] Update all files with inconsistent naming conventions.
- [ ] Test all files to ensure that they are working correctly.

## Deadline

Preliminary deadline: 1.0.1 milestone.

## References

: [CSS Naming Conventions That Will Save You Hours of Debugging](https://www.freecodecamp.org/news/css-naming-conventions-that-will-save-you-hours-of-debugging-35cea737d849/)
