### ISSUE TITLE
Add Role-based access control

### ISSUE THREAD

**Issue by HampusAndersson01** [HampusAndersson01/Parameter-Database#137]
### Description
Capability to create, update and delete parameters shall be controlled certain roles.

### Acceptance Criteria
- A user with the "admin" role can create, update and delete parameters. Can also edit user roles.
- A user with the "editor" role can update ,create and delete parameters.
- A user with the "viewer" role can only view parameters.

### Tasks
- [ ] Update the parameter creation form to automatically log in using Volvo's existing system.
- [ ] Update the parameter update form to only allow users with the correct role to make changes.
- [ ] Update the Open/Delete column to only show delete with > editor role

### Additional Information
This feature will help us better manage our parameters and ensure that only authorized users can make changes. Please ask Gillis for more information about Volvo's existing system

**Comment by HampusAndersson01** [comment]
What system should be used for authentication?
