### ISSUE TITLE
Create parameter page

### ISSUE THREAD

**Issue by HampusAndersson01** [HampusAndersson01/Parameter-Database#85]
### TODO
- [x]  Modify Rigfamily count
- [x] Fix Datestring being empty
- [x] Fix HampusAndersson01/Parameter-Database#55 
- [x] Editable images
- [x] Editable possible values
- [x] HampusAndersson01/Parameter-Database#53

**Comment by HampusAndersson01** [comment]
### Proposed layout


![Image](https://user-images.githubusercontent.com/1824032/230374601-1335f377-fcb2-4562-b99b-dfd0299596d5.png)
